# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading 

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [1]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [4]:
# Import torch
import torch

# Create random tensor
tensor_a = torch.rand(7,7)
tensor_a, tensor_a.shape

(tensor([[0.1516, 0.1795, 0.1374, 0.2276, 0.7874, 0.8158, 0.5247],
         [0.4563, 0.1959, 0.8284, 0.1536, 0.6178, 0.0728, 0.1148],
         [0.5174, 0.9706, 0.2173, 0.1676, 0.2982, 0.4861, 0.1598],
         [0.0066, 0.7199, 0.8253, 0.4830, 0.9662, 0.0281, 0.0471],
         [0.1333, 0.2802, 0.6081, 0.2551, 0.6117, 0.7879, 0.8325],
         [0.7781, 0.4437, 0.0709, 0.9895, 0.5802, 0.8634, 0.9043],
         [0.9818, 0.3331, 0.7899, 0.2944, 0.1587, 0.8494, 0.2562]]),
 torch.Size([7, 7]))

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [7]:
# Create another random tensor
tensor_b = torch.rand(1,7)

# Perform matrix multiplication 
print(f"tensor_a shape = {tensor_a.shape}")
print(f"tensor_b.T shape = {tensor_b.T.shape}")
mult_ans = torch.matmul(tensor_a, tensor_b.T)
mult_ans, mult_ans.shape

tensor_a shape = torch.Size([7, 7])
tensor_b.T shape = torch.Size([7, 1])


(tensor([[0.5263],
         [1.0229],
         [0.9601],
         [0.9308],
         [0.8506],
         [1.3680],
         [1.5587]]),
 torch.Size([7, 1]))

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [ ]:
# Set manual seed
SEED = 0
torch.manual_seed(SEED)

# Create two random tensors
ten_c = torch.rand(7,7)

# torch.manual_seed(SEED) ## uncomment this t0 get d = first row of c
ten_d = torch.rand(1,7)

# Matrix multiply tensors
print(f"tensor c = {ten_c},\n and its shape = {ten_c.shape}")
print("=======================================================")
print(f"tensor d = {ten_d},\n and its shape = {ten_d.shape}")
print("=======================================================")
print(f"tensor d.T = {ten_d.T},\n and its shape = {ten_d.T.shape}")
print("=======================================================")



mult_ans = torch.matmul(ten_c, ten_d.T)
mult_ans, mult_ans.shape

tensor c = tensor([[0.4963, 0.7682, 0.0885, 0.1320, 0.3074, 0.6341, 0.4901],
        [0.8964, 0.4556, 0.6323, 0.3489, 0.4017, 0.0223, 0.1689],
        [0.2939, 0.5185, 0.6977, 0.8000, 0.1610, 0.2823, 0.6816],
        [0.9152, 0.3971, 0.8742, 0.4194, 0.5529, 0.9527, 0.0362],
        [0.1852, 0.3734, 0.3051, 0.9320, 0.1759, 0.2698, 0.1507],
        [0.0317, 0.2081, 0.9298, 0.7231, 0.7423, 0.5263, 0.2437],
        [0.5846, 0.0332, 0.1387, 0.2422, 0.8155, 0.7932, 0.2783]]),
 and its shape = torch.Size([7, 7])
tensor d = tensor([[0.4820, 0.8198, 0.9971, 0.6984, 0.5675, 0.8352, 0.2056]]),
 and its shape = torch.Size([1, 7])
tensor d.T = tensor([[0.4820],
        [0.8198],
        [0.9971],
        [0.6984],
        [0.5675],
        [0.8352],
        [0.2056]]),
 and its shape = torch.Size([7, 1])


(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]),
 torch.Size([7, 1]))

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [13]:
# Set random seed on the GPU
torch.cuda.manual_seed(1234)


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [15]:
# Set random seed
torch.cuda.manual_seed(1234)

# Check for access to GPU
device = "cuda" if torch.cuda.is_available() else "cpu"
print(f"Device: {device}")
# Create two random tensors on GPU
tensor_A = torch.rand(size=(2,3)).to(device)
tensor_B = torch.rand(size=(2,3)).to(device)
tensor_A, tensor_B

Device: cpu


(tensor([[0.5932, 0.1123, 0.1535],
         [0.2417, 0.7262, 0.7011]]),
 tensor([[0.2038, 0.6511, 0.7745],
         [0.4369, 0.5191, 0.6159]]))


### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [7]:
# Perform matmul on tensor_A and tensor_B


### 8. Find the maximum and minimum values of the output of 7.

In [17]:
# Find max
print(f" max = {torch.max(mult_ans)}")

# Find min
print(f" min = {torch.min(mult_ans)}")

 max = 3.0481479167938232
 min = 1.7067397832870483


### 9. Find the maximum and minimum index values of the output of 7.

In [18]:
# Find arg max
print(f" max = {torch.argmax(mult_ans)}")

# Find arg min
print(f" min = {torch.argmin(mult_ans)}")

 max = 3
 min = 4



### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [19]:
# Set seed
SEED = 7
torch.manual_seed(SEED)

# Create random tensor
ten_1 = torch.rand(1,1,1,10)

# Remove single dimensions
ten_minus_1 = torch.squeeze(ten_1)

# Print out tensors and their shapes
print(f"tensor with 1 = {ten_1},\nand its shape ={ten_1.shape}")
print(f"tensor without 1 = {ten_minus_1},\nand its shape ={ten_minus_1.shape}")

tensor with 1 = tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]),
and its shape =torch.Size([1, 1, 1, 10])
tensor without 1 = tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]),
and its shape =torch.Size([10])
