In [1]:
import numpy as np

In [2]:
arr_1 = np.array([1, 2, 3])
arr_1

array([1, 2, 3])

In [3]:
arr_2 = np.zeros(3)
arr_2

array([0., 0., 0.])

In [4]:
arr_3 = np.ones(3)
arr_3

array([1., 1., 1.])

In [5]:
arr_4 = np.full(3, fill_value= 7)
arr_4

array([7, 7, 7])

In [6]:
arr_5 = np.arange(5, 50, 5)
arr_5

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45])

In [7]:
arr_6 = np.linspace(0, 1, 5, retstep=True)
arr_6

(array([0.  , 0.25, 0.5 , 0.75, 1.  ]), np.float64(0.25))