In [2]:
import numpy as np

1. Write a NumPy program to create an array of 10 zeros, array of 10 ones, and array of 10 fives. 

In [3]:
arr_zeros = np.zeros(10)
arr_ones = np.ones(10)
arr_fives = np.ones(10)*5

arr_zeros, arr_ones, arr_fives

(array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]),
 array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]),
 array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.]))

---

2. Write a NumPy program to create an array of all even integers from 30 to 70. 

In [4]:
arr_evens = np.arange(30, 71, 2)
arr_evens

array([30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62,
       64, 66, 68, 70])

---
3. Write a NumPy program to create an array of given shape (5,6) and integer type, filled with zeros. 

In [5]:
arr_zeros = np.zeros((5, 6))
arr_zeros

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

---
4. Create a 10x10 array with random values and find the minimum and maximum values. 

In [6]:
arr_rand = np.random.randint(0, 100, size = (10, 10) )
arr_rand, arr_rand.min(), arr_rand.max()

(array([[24, 91, 79,  7, 79, 54, 38,  3, 62, 67],
        [62,  8, 48, 88, 27, 65, 80, 31, 12,  7],
        [ 9, 33, 67, 35, 71, 72, 56, 17, 87, 41],
        [71, 98, 90, 26, 69, 94, 72, 44, 10, 72],
        [13, 85, 47, 23, 69, 48, 31, 14, 26, 58],
        [29, 70, 12, 99, 48,  6, 48, 50, 49, 90],
        [47, 35, 78, 12, 74, 44, 54, 14, 35, 49],
        [33, 41, 47, 12, 57, 43, 83, 10, 43, 88],
        [11, 86, 42,  4, 87, 96, 30, 52, 87, 46],
        [97, 29, 52, 67, 60, 52,  0, 80, 84, 87]], dtype=int32),
 np.int32(0),
 np.int32(99))

---
5. Write a NumPy program to create a 3x3 array with values ranging from 2 to 10. 

In [7]:
arr = np.random.randint(2, 11, size = (3, 3))
arr

array([[ 2,  4,  9],
       [ 6,  5, 10],
       [ 4,  4,  3]], dtype=int32)

---
6. Write a NumPy program to create an array of size = 20 using arrange, then extract all numbers from a given array greater than 15. 

In [8]:
arr = np.arange(20)
arr[arr>15]

array([16, 17, 18, 19])

---
7. Write a NumPy program to combine the two 2-dimensional arrays using hstack and vstack. 

Array 1: [[0, 1, 3], [5, 7, 9]] 

Array 2: [[0, 2, 4], [6, 8, 10]] 

In [9]:
arr_1 = np.array( [[0, 1, 3], 
                [5, 7, 9]] )  # 2x3

arr_2 = np.array( [[0, 2, 4],
                [6, 8, 10]] ) # 2x3

arr_hstack = np.hstack( (arr_1, arr_2) )
arr_vstack = np.vstack( (arr_1, arr_2) )

arr_hstack, arr_vstack

(array([[ 0,  1,  3,  0,  2,  4],
        [ 5,  7,  9,  6,  8, 10]]),
 array([[ 0,  1,  3],
        [ 5,  7,  9],
        [ 0,  2,  4],
        [ 6,  8, 10]]))

---
8. Write a NumPy program to create ones array of size 10 and change the 6th element to 11. 

In [10]:
arr = np.ones(10)
arr[5] = 11
arr

array([ 1.,  1.,  1.,  1.,  1., 11.,  1.,  1.,  1.,  1.])

---
9. Write a NumPy program to reverse an array [using two different methods]. 

In [11]:
arr = np.array([1,  4,  5,  7])
#               0,  1,  2,  3
#              -4, -3, -2, -1

arr_reverse =  np.array( [arr[ -(i+1) ] for i in range(len(arr))] )
arr_reverse

array([7, 5, 4, 1])

In [12]:
arr_reverse = np.flip(arr)
arr_reverse

array([7, 5, 4, 1])

In [ ]:
arr_reverse = np.array( [arr[::-1]] )
arr_reverse

array([[7, 5, 4, 1]])